### ISSUE TITLE
How to print a table component in two pages

### ISSUE THREAD

**Issue by sai78** [MatthewHerbst/react-to-print#179]
I am using react-to-print npm package to print react components. I want to print a component which is having two table and I want to print each table in different page. The table components are having scroll. I used **page-break-after** property in **media query** still I am not able to print two tables in two different pages .

Code sample is here:  https://codesandbox.io/s/react-to-print-ig9g9  

Thanks in advance

**Comment by MatthewHerbst** [comment]
Not sure I know enough about how that property works. I think you may want to ask this question on StackOverflow, unless you think that there is a bug in this library causing the property to not work?

Does it work when printed not using `react-to-print`?

**Comment by ghost** [comment]
```html
<ReactToPrint
      bodyClass="patchPrintStyle"
      trigger={() => <Button disabled={canPrint} type="primary">打印</Button>}
      content={() => this.patchContent}
/>
```

```css
:global {
    .patchPrintStyle {
        section {
            display: block !important;
        }
        article {
            height: 100% !important;
        }
        * {
            border: 0 none !important;
        }
    }
}
```
