### ISSUE TITLE
Footer on content in Safari.

### ISSUE THREAD

**Issue by AlexandrHovsepyan** [MatthewHerbst/react-to-print#271]
Hello there, I am using "React-to-print" 2.9.0 package.
And I would like to have a fixed footer on each page while printing, which will contain a picture and a text. This works on every browser, except for Safari.
I have got the following issue on Safari:
when I create a fixed element, that element overlaps the file content on the first page.
I can see that fixed element on the first page only: it is not visible on any other page.

**Comment by MatthewHerbst** [comment]
Hello. Thanks for using the library. Could you please share an (ideally working) code sample? I can't profess to being a CSS expert, so you might want to also ask your question on StackOverflow to get a bit more help

**Comment by AlexandrHovsepyan** [comment]
Thanks for answer.

This is HTML.
```html
<div class="_1J4LNasiXggOGUhggrZ6YE">
  <img src="/static/img/logo.svg" alt="logo">
  <p>Projektet skapades med iPlanner.se</p>
</div>
```

And CSS
```css
.page-footer {
    display: none;
    position: fixed;
    bottom: 1rem;
    left: 0px;
    width: 100%;
    text-align: center;
    font-size: .7rem;
    color: $brand-secondary;
    border-top: 2px solid #e4e4e4;
    padding-top: 8px;
    > p {
     margin-top: 8px;
    }
    @media print {
      display: block;
    }
  }
  @media print {
    padding: 1rem 3rem 100px 3rem;
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
              appearance: none;
    }
    input[type=number] {
      -moz-appearance:textfield;
    }
  }
}
.footer, .footer-space {
  height: 0px;
  @media print {
    height: 90px;
  }
```
