### ISSUE TITLE
Page size is not correct

### ISSUE THREAD

**Issue by pyjun01** [MatthewHerbst/react-to-print#325]
Hi,

page and element are the same size, but the bottom has padding bottom, so the bottom part of the element is on the next page.
please check this

Page css
```css
@page {
  size: 80mm 50mm;
  width: 80mm;
  height: 100%;
  margin: 0mm;
}
```

Element css
```css
.test > div:not(.pagebreak) {
  width: 80mm;
  height: 50mm;
  overflow: hidden;
  background-color: #000;
  color: #fff;
}
```

result
![image](https://user-images.githubusercontent.com/32596517/101472782-5f2e3300-398c-11eb-9692-adbf94114b90.png)

https://codesandbox.io/s/print-break-page-reactclicktoprint-forked-ivies?file=/src/styles.css

**Comment by MatthewHerbst** [comment]
We copy the styles exactly as they are on the page, so this is some CSS issue you are having. I have made it almost perfect with the below CSS. Not sure why there is still a little on the bottom of the second page. Will try more tonight, but you might get more help asking on StackOverflow

```css
.App {
  font-family: sans-serif;
  text-align: center;
}

@media all {
  .pagebreak {
    display: none;
  }
}

@media print {
  html,
  body {
    /* height: initial !important; */
    /* overflow: initial !important; */
    /* -webkit-print-color-adjust: exact; */
    background-color: #eee;
    margin: 0;
  }
}

@media print {
  .pagebreak {
    /* margin-top: 1rem; */
    /* display: block; */
    page-break-before: always;
  }

  .test > div:not(.pagebreak) {
    width: 100%;
    height: 100%;
    /* overflow: hidden; */
    background-color: #000;
    color: #fff;
    padding-left: 1mm;
    margin: 0;
  }
}

@page {
  size: 80mm 50mm;
  /* width: 80mm; */
  /* height: 100%; */
  /* margin: 0; */
  /* padding: 0; */
}
```
