### ISSUE TITLE
Page Template

### ISSUE THREAD

**Issue by taynancid** [MatthewHerbst/react-to-print#326]
Hello,
Is it possible to have a template for each page that will result when printing (like the same header for each page)?

**Comment by MatthewHerbst** [comment]
You can use CSS to style the pages however you want, such as by hiding a header component when not printing and then when printing show the component:

```css
.header {
  display: none;
}

// Only applies when printing
@media print {
  .header {
    display: block;
  }
}
```
