### ISSUE TITLE
Custom footer and header

### ISSUE THREAD

**Issue by MassoudSharifi** [MatthewHerbst/react-to-print#387]
I want to print a list of products. I want to print the date and name of the company on the footer of each page and remove the existing footer and Header

**Comment by MatthewHerbst** [comment]
Hello. What is your question or problem you are having with the library?

**Comment by MassoudSharifi** [comment]
<img width="547" alt="jurnal" src="https://user-images.githubusercontent.com/43839019/122171928-83b41c00-ce95-11eb-8cab-6c2fab39b194.PNG">
@MatthewHerbst  How to edit the ringed places in the image

**Comment by MatthewHerbst** [comment]
Did you modify the `pageStyle` prop? The default value has a style that removes the header/footer:

```js
pageStyle: "@page { size: auto;  margin: 0mm; } @media print { body { -webkit-print-color-adjust: exact; } }", // remove date/time from top
```

**Comment by MassoudSharifi** [comment]
@MatthewHerbst I remove the default footer and header but I cannot add a custom footer for multiple pages

**Comment by MatthewHerbst** [comment]
Can you please share the code you are using? Very difficult for me to help otherwise

**Comment by MassoudSharifi** [comment]
@MatthewHerbst Yes, the code is here. and also want to add page numbers in the footer of each page
https://codesandbox.io/s/awesome-brook-0bhtg?file=/src/example/index.js:107-112

**Comment by MassoudSharifi** [comment]
@MatthewHerbst Can you help me with how to solve this problem ????

**Comment by MatthewHerbst** [comment]
Apologies, I was traveling and not working.

It does seem there is a bug with `pageStyle`, I'm looking into that now. You don't have to use `pageStyle`, and I actually plan to remove it in the next major release. Just use `@media print { ... }` in your existing CSS and set styles there.

In terms of creating a footer/header, there are two options beyond what you are trying to do. The first is to use a table (example: https://plnkr.co/edit/lWk6Yd?preview). The second is to use the new CSS 3 Page Margin Boxes (see spec + examples here: https://www.w3.org/TR/css-page-3/#margin-boxes)

I will update once I know more about the bug, it's very strange

**Comment by MassoudSharifi** [comment]
@MatthewHerbst how to use CSS 3 Page Margin Boxes. is there a library to install? because nothing working without  page size property in CSS

**Comment by MatthewHerbst** [comment]
I'm honestly not sure, I had never heard of them until I was researching your problem. Asking on StackOverflow might be best for that. Apologies for the delayed response, I have had to focus on work the last two weeks. I hope to be able to get some time in for this library this coming weekend.

**Comment by clydebaron2000** [comment]
A follow up on page margin boxes support?

**Comment by Dmitriy-Krivetsky** [comment]
Maybe it will help someone
Through this function, I was able to make a watermark on all pages, as well as the header and the footer.

```jsx
 const handlePrint = useReactToPrint({
   content: () => {
      const tableStat = tableStatRef.current.cloneNode(true);
      const PrintElem = document.createElement('div');
      const header = 
        `<img src="${logo}" alt="" class="watermark"/>` + 
        `<div class="page-footer">I'm The Footer</div>`;
      PrintElem.innerHTML = header;
      PrintElem.appendChild(tableStat);
      return PrintElem;
    },
});
```

```css
@media print {
  .watermark {
    position: fixed;
    top: 50vh;
    z-index: 9;
    width: 50vw;
    page-break-after: always;
    left: 50%;
    transform: translate(-50%, -50%);
    opacity: .1;
  }
  div.page-footer {
    position: fixed;
    z-index: 9;
    bottom: 0;
    width: 100%;
    height: 50px;
    font-size: 15px;
    color: #fff;
    background: red;
    opacity: 0.5;
    page-break-after: always;
  }
}
```

for me, the key values were:
```css
page-break-after: always;
z-index: 9;
```

https://github.com/gregnb/react-to-print/issues/323#issuecomment-946773228

**Comment by sadidul012** [comment]
This code worked for me with a watermark, sticky footer, header for each page

HTML
```html
            <img alt={""} src={logo} className={"watermark"}/>
            <table className="report-container">
                <thead className="report-header">
                <tr>
                    <th className="report-header-cell">
                        <div className="header-info">
                            header content....
                        </div>
                    </th>
                </tr>
                </thead>
                <tfoot className="report-footer">
                <tr>
                    <td className="report-footer-cell">
                        <div className="footer-info">
                            <div className={"page-footer"}>
                                footer content....
                            </div>
                        </div>
                    </td>
                </tr>
                </tfoot>
                <tbody className="report-content">
                <tr>
                    <td className="report-content-cell">
                        <div className="main">
                            body content...
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
```
CSS
```css
div.page-footer {
    text-align: center;
    height: 50px;
    font-size: 10px;
    opacity: 0.8;
    position: fixed;
    bottom: 0;
    width: 100%;
}

div.page-footer p {
    margin: 0;
}

.watermark {
    display: none;
    top: 50vh;
    z-index: -9;
    width: 50vw;
    page-break-after: always;
    left: 50%;
    transform: translate(-50%, -50%);
    opacity: .1;
}

table.report-container {
    page-break-after: always;
    width: 100%;
}

thead.report-header {
    display: table-header-group;
}

tfoot.report-footer {
    display: table-footer-group;
}

div.footer-info, div.page-footer {
    display: none;
    height: 60px;
}


@media print {
    @page {
        size: A4;
        margin: 16mm 16mm 16mm 16mm;
    }

    .watermark {
        display: block;
        counter-increment: page;
        position: fixed;
    }

    div.page-footer, div.footer-info {
        display: block;
    }
}
```
