### ISSUE TITLE
A4 paper sizing not work

### ISSUE THREAD

**Issue by KimTrongNguyen** [MatthewHerbst/react-to-print#406]
Hello, I'm using react-to-print to print on A4 paper. Base on the requirement, I need to specify some element in the page in centimeter. So I begin with the page itself and the page always smaller than A4 size. How can I make the paper to be A4 size?
Thank you so much!
**ReactToPrint code:**
```jsx
import React, { useRef } from 'react';
import ReactToPrint from 'react-to-print';
import "../asset/css/component.css";

export default function Print(props) {
  const printPreviewRef = useRef();

  return (
    <div>
      <ReactToPrint
        trigger={() => <button>Print this out!</button>}
        content={() => printPreviewRef.current}
      />
      <div className="print-preview" ref={printPreviewRef}>
      </div>
    </div>
  );
};
```
**CSS for styling: (component.css)**
```css
@page {
    size: A4;
    margin: 0;
}

@media print {
    body, html {
        width: 21cm !important;
        height: 29.7cm !important;
        margin: 0;
    }
    .print-preview {
        width: 21cm;
        height: 29.7cm;
        margin: 0;
        border: 5px solid #000;
    }
}
```
The result (Firefox):
![Capture](https://user-images.githubusercontent.com/88039354/129131602-7cf03bf8-c166-413f-a0d8-5a796eb5858d.PNG)
