### ISSUE TITLE
Print a component on the fly

### ISSUE THREAD

**Issue by meness** [MatthewHerbst/react-to-print#426]
Hey,

First, thanks for this great library. I'm planning to print a component on the fly. The component is not going to be rendered when the user first sees the page. The component is only useful for printing which has a long table, but the page the user sees is a compact version of the table which has pagination.

How can I render a component for ReactToPrint on the fly? Something like this:

```jsx
const printHandler = useReactToPrint();

const onPrintClick = ()=>{

printHandler.print(<PrintableComponent />);

}

**Comment by MatthewHerbst** [comment]
Hello, glad you're enjoying it! There are a two ways to do what you're looking for.

Option 1: have the component appear only when being printed using CSS:
```css
.PrintableComponentClassName {
  display: none;
}

/* Styles within this directive only apply when the document is being printed */
@media print {
  .NormalPageComponentClassName {
    display: none;
  }

  .PrintableComponentClassName {
    /* show component, example */
    display: block;
  }
}
```

Option 2: use the `onBeforeGetContent` prop to change your page during print:
```jsx
const [printing, setPrinting] = useState(boolean);
const onBeforeGetContentResolve = useRef();

const printHandler = useReactToPrint({
  onBeforeGetContent: () => {
    return new Promise((resolve) => {
      // Save the Promise.resolve to call after the state update is completed
      onBeforeGetContentResolve.current = resolve;
    });
  },
  onAfterPrint:() => {
    setPrinting(false);
  },
});

useEffect(() => {
  if (printing === true && typeof onBeforeGetContentResolve.current === "function") {
    // Resolve the Promise, letting react-to-print know the state change has completed and it's ok to print
    onBeforeGetContentResolve.current();
  }
}, [onBeforeGetContentResolve.current, printing]);

return (
  <div>
    {printing && <PrintableComponent />}
    (!printing && <NormalPageComponent />}
  </div>
);
```

I hope that makes sense, please let me know if it doesn't.
