### ISSUE TITLE
Component breaks at random places in the print dialog

### ISSUE THREAD

**Issue by hank-cmd** [MatthewHerbst/react-to-print#447]
Hello there, 

_Thanks for working on this project !_ :-)

**Problem:**
I want to print my whole component in one page, instead of multiple pages. Is this possible ?
Otherwise, i would like to be able to choose where to break the page in the print dialog. Is this possible?

**Desktop site demo:**
https://icqqr.csb.app/
_Print button is at the bottom of the page_

**codesandbox repo:** 
https://codesandbox.io/s/react-to-print-issue-code-icqqr?file=/src/Resume.js

**Codesandbox code structure:**
- The Resume component contains jsx that's styled with styled components.
- The Resume component is imported into the ExportPdfComponent.
- The ExportPdfComponent contains the Resume component and react-to-print button.
- The ExportPdfComponent is imported into the App.js.

**Comment by MatthewHerbst** [comment]
Hi, and thanks for using the library. We have a [Page Breaks](https://github.com/gregnb/react-to-print#page-breaks) section of the README that has a lot of useful information. You can change the page size using CSS such as:

```css
@page {
  size: A4;
  margin: 0;
}
@media print {
  html, body {
    width: 210mm;
    height: 297mm;
  }
  /* ... the rest of the rules ... */
}
```

You can chose where you want the page breaks using the CSS `page-break-after`, `page-break-before`, or `page-break-inside` properties. Hope that helps
