### ISSUE TITLE
How to remove URL after print pdf and staying number pages ?

### ISSUE THREAD

**Issue by duyanh4788** [MatthewHerbst/react-to-print#448]
Dear .

I want remove URL after print PDF and staying number page , I have tried many ways but not done

Please help me ,  

Thanks you so much

![image](https://user-images.githubusercontent.com/75610658/147332426-22591983-7350-4cb8-a843-89f177fa6b16.png)

**Comment by MatthewHerbst** [comment]
To remove the date/time from the top you can use 

```css
@page {
  size: auto; 
  margin: 0mm;
}
@media print {
  body {
    -webkit-print-color-adjust: exact;
  }
}
```

For the others I'm not sure, it depends on the browser you are using. The browser normally controls page numbers so that's not something you normally need to use CSS for.

Which browser are you using?

**Comment by duyanh4788** [comment]
Hi MatthewHerbst .

Thanks you forward , 

The browser using google chrome . and i want remove url

**Comment by MatthewHerbst** [comment]
Have you changed any of the CSS? If you look at the official example we have on Google Chrome it does not print the URL: https://codesandbox.io/s/rzdhd

**Comment by duyanh4788** [comment]
Hi MatthewHerbst .

I have changed CSS is code : 

```css
#tFootPdf::after {
    counter-increment: page;
    content: counter(page);
 }
```
But not working , please help me
