### ISSUE TITLE
How to remove URL printRef.current

### ISSUE THREAD

**Issue by duyanh4788** [MatthewHerbst/react-to-print#453]
Dear .

I have `console.log(printRef.current)` and see URL , have ideal remove baseURI in (`printRef.current`)

![image](https://user-images.githubusercontent.com/75610658/147721381-4010c966-9720-4df1-bab5-eaf59a7e8a0a.png)

**Comment by MatthewHerbst** [comment]
Sorry, what is the question here?

**Comment by duyanh4788** [comment]
Dear .

I console.log(printRef.current) and see baseURI , I want remove baseURI after printing . 
![image](https://user-images.githubusercontent.com/75610658/147815653-89d4704b-6455-4527-8975-54a472a52898.png)

Thanks you .

**Comment by MatthewHerbst** [comment]
The default CSS already does that. What CSS have you changed?

**Comment by duyanh4788** [comment]
This is my code css .

```css
@page {
  size: auto; 
  margin: 30px 40px 35px 40px;
}

@media print {
  html,
  body {
    height: initial !important;
    overflow: initial !important;
  }
}
```

**Comment by MatthewHerbst** [comment]
The styles that we apply are:

```css
@page {
  size: auto;
  margin: 0mm;
}

@media print {
  body {
    -webkit-print-color-adjust: exact;
  }
}
```

Setting the page margin to 0 is how we remove the URL. I don't know another way to do it unfortunately. Might be a good question to ask on StackOverflow
