### ISSUE TITLE
How can fill every page 

### ISSUE THREAD

**Issue by Brenerss** [MatthewHerbst/react-to-print#494]
I have this pdf and i need fill the left column with black color, like download  curriculum of Linkedin 

![image](https://user-images.githubusercontent.com/53789728/168890473-7e13a6f5-2cb4-480e-80dd-9b36e1b19683.png)

**Comment by MatthewHerbst** [comment]
Hello. Can you please share your code, and more about what you are trying to do? `react-to-print` cannot modify a PDF file

**Comment by Brenerss** [comment]
of course,

```css
@media print {
  @page {
    size: A4;
    margin: 16mm 16mm 16mm 16mm;
  }
}

.example3-container { 
  display: grid;
  grid-template-columns: 30% 1fr;

  .left-content {
    background-color: #000;
  }
}
```

```jsx
export default forwardRef((props, ref) => {
  return (
    <div
      ref={ref}
      className={`example3-container ${
        props.isPreview
          ? 'example3-container-preview'
          : 'example3-container-pdf'
      }`}
    >
      <section className="left-content">
                     ....
      </section>
      <section className="right-content">
                     .....
      </section>
  );
});
```
