### ISSUE TITLE
CSS `background-clip` properties not displayed correctly

### ISSUE THREAD

**Issue by dudenhot** [MatthewHerbst/react-to-print#530]
In the **current version**, a text with the following css does only show the background image but not the text (Microsoft Edge
Version 105.0.1343.50):
```html
<div class="title">TITLE</div>
```
```css
.title {    
    background-clip: text;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    color: transparent;
    background-image: linear-gradient(0deg, #45819D, #7FB0C5);
    font-weight: bold;
    font-size: 25px;
}
```

![image](https://user-images.githubusercontent.com/114644099/192961973-71c1353e-6cbc-424b-94fb-8b6b55cfe903.png)

print window with **version 1.0.10** (it works almost correctly, except the line above the text)
![image](https://user-images.githubusercontent.com/114644099/192962177-d07cb814-6d9b-410a-bf09-ad3f3b65bbf0.png)

print window with **current verion**, only background image displayed:
![image](https://user-images.githubusercontent.com/114644099/192963015-4d4b10f0-591d-4cd9-a378-cc88dc637de7.png)
