### ISSUE TITLE
Is there a way to show the page number besides the default one?

### ISSUE THREAD

**Issue by diego-cor** [MatthewHerbst/react-to-print#536]
I want to show this at the footer of every page
![image](https://user-images.githubusercontent.com/112601691/196390687-a93e0849-c5cb-4bf0-b4d3-10ae8b1f15b3.png)

I am following [this css code](https://stackoverflow.com/questions/20050939/print-page-numbers-on-pages-when-printing-html) I found 

```css
#content {
  display: table;
}

#pageFooter {
  display: table-footer-group;
}

#pageFooter:after {
  counter-increment: page;
  content: counter(page);
}
```

but it always returns 1 as the counter instead of the other numbers. Can anyone help me?
