### ISSUE TITLE
Root-component border is cutoff

### ISSUE THREAD

**Issue by tyometarou** [MatthewHerbst/react-to-print#587]
<img width="850" alt="スクリーンショット 2023-02-15 13 51 51" src="https://user-images.githubusercontent.com/58591760/218939469-3b870f9e-75fc-40aa-a80b-9851ab3f88d8.png">

Long time no see!
react-to-print is very good library

sorry i couldn't reply about 1px solid issue last year、、、
so this issue was closed

A lot of time passed since then. 

I was able to reproduce the phenomenon!

https://codesandbox.io/s/react-to-print-forked-gd8onz?file=/example.css:200-285

I did only two things

at your example code 
example css
modify relativeCSS and testClass 
```css
.relativeCSS {
  border: solid 1px #707070;
}

.testClass {
  background: #e6ebed;
}
```
in this case

border-color  #707070 is very light　on the #e6ebed　 in the print preview

**Comment by MatthewHerbst** [comment]
Hi! Thanks for re-reporting, and for the example!

The issue seems to the the `margin: 0` we set as the default style: 

https://github.com/gregnb/react-to-print/blob/e739ca293af22c2af99054c2d81235c5526ec49f/src/index.tsx#L29-L41

Taking your example, first, I made these changes to make the issue easier to see:

```css
.relativeCSS {
  border: solid 5px #707070;
}

.testClass {
  background: red;
  border: solid 5px green;
}
```

Then, in `examples/ClassComponent/index.js`, on the `ReactToPrint` component, I set `pageStyle=""` to override the default style we set. Doing that fixes the border problem, but then shows things we don't want people to see like the url, page number, title, etc.

Not sure what a good fix will be here, let me think about it
