### ISSUE TITLE
In react-to-print it is not able to print something that is style={{display:"none"}}

### ISSUE THREAD

**Issue by MarcusCody** [MatthewHerbst/react-to-print#604]
![image](https://user-images.githubusercontent.com/104601262/229497488-5e101238-de23-437e-a9e1-6d9c1126548d.png)
![image](https://user-images.githubusercontent.com/104601262/229497505-b1f488ee-42d0-438c-bcfa-d9fa019a33c3.png)

**Comment by MatthewHerbst** [comment]
Hello. `react-to-print` can only print things that are visible. The recommended approach here is to remove the `display: none` while printing using a media query. Something like:

```css
.myClass {
  display: none;
}

@media print {
  .myClass {
    display: block;
  }
}
```
