### ISSUE TITLE
SCSS Style is not working for component

### ISSUE THREAD

**Issue by vaibhav135** [MatthewHerbst/react-to-print#631]
react-to-print version: v2.14.13

Currently using SCSS for styling and it doesn't work.

> Although inline styling is working

Here's my component to print

``` javascript
export const ComponentToPrint = forwardRef<HTMLDivElement>(({}, ref) => {
  return (
    <div className="component-to-print" ref={ref}>
      <h1>Hello</h1>
    </div>
  );
});
```

```scss
// SCSS for component to print
.component-to-print { 
  display: none;
}

@media print{
  .component-to-print { // div.component-to-print h1 {....} will also not work
     display: block;
     color: red;
     background-color: blue;
  }
}
```

Here's the parent Component

```javascript
export const ParentComponent = () => {
 const componentRef = useRef(null);

 const handlePrint = useReactToPrint({
    content: () => {
      return componentRef.current;
    },
    copyStyles: true,
 });

  return (
    <div className="parent-component">
        <ComponentToPrint ref={componentRef} />
        <button onClick={handlePrint}> Click </button> 
    </div>
  );
});
```

So Right now for the above mentioned code, the page is blank. But as soon as I make the `copyStyles: false`. It shows in the print.
 
I've tried the following solutions- https://github.com/gregnb/react-to-print/issues/410 | https://github.com/gregnb/react-to-print/issues/455 | https://github.com/gregnb/react-to-print/issues/11  . But didn't help me much.
