### ISSUE TITLE
multiple page in mobile device

### ISSUE THREAD

**Issue by samirahosseini937** [MatthewHerbst/react-to-print#761]
i use this style 
```css
@media print {
  /* Hide all elements except the certificate */
  body * {
    visibility: hidden; /* Hide all elements */
    page-break-inside: avoid; /* Prevent breaking inside */
  }

  /* Show only the certificate */
  .certificate {
    visibility: visible;
    page-break-inside: avoid; /* Prevent breaking inside */
  }

  /* Ensure all children of the certificate are visible */
  .certificate * {
    visibility: visible;
  }
}
```

and print with 
```tsx
  const handlePrint = useReactToPrint({
    contentRef: certificateRef as React.MutableRefObject<HTMLElement>,
  });
  ```
  
  
  why in mobile device create 5 page instead of one page
